# run with make test
version: '3'
services:
  test:
    environment:
      TERM: ${TERM}
    env_file:
      .env
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - ckan

  nginx-harvest-source:
    image: nginx
    volumes:
      - ./tests/harvest-sources:/usr/share/nginx/html

  ckan:
    links:
      - nginx-harvest-source