version: 2.1
jobs:
  bat_test:
    machine: 
      docker_layer_caching: true 
    steps:
      - checkout
      - run: make test
      
  build:
    machine: 
      docker_layer_caching: true 
    steps:
      - checkout
      - run: make build ci
      - run: make lint-all
      - run: make test-extensions
      
  deploy-sandbox:
    docker:
      - image: circleci/python:3.6
    environment:
      JENKINS_URL: https://ci.sandbox.datagov.us
    steps:
      - checkout
      - deploy:
          name: Trigger Jenkins deploy
          command: bin/jenkins_build deploy-ci-app-catalog-next
  
  test_importer: 
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: tests 
          command: make test-import-tool
  
  start_ckan_28:
    machine:
      image: circleci/classic:201708-01
    steps:
      - checkout
      - run:
          name: Start CKAN 2.8
          command: |
            cd tools/ci-scripts
            ./circleci-build-catalog-next.bash
  
  docker_publish:
    machine: true
    steps:
      - checkout
      - run:
          name: Tag and publish image
          command: |
            docker build -t datagov/catalog-next:latest ckan/
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push datagov/catalog-next:latest

      
workflows:
  version: 2
  commit:
    jobs:
      - start_ckan_28
      - build
      - deploy-sandbox:
          requires:
            - build
          filters:
            branches:
              only: master
      - test_importer
      - bat_test
      - docker_publish:
          requires:
            - build
          filters:
            branches:
              only: master
