version: 2.1

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: build
          command: make build
      - run:
          name: Archive Catalog Docker image
          command: docker save -o image-catalog.tar datagov/catalog.data.gov:latest
      - run:
          name: Archive Solr Docker image
          command: docker save -o image-solr.tar datagov/catalog.data.gov.solr:latest
      - run:
          name: Archive DB Docker image
          command: docker save -o image-db.tar datagov/catalog.data.gov.db:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./image-catalog.tar
            - ./image-solr.tar
            - ./image-db.tar
      - run: 
          name: lint and test
          command: |
            docker-compose up -d
            make lint-all
            make quick-bat-test
    
  deploy-sandbox:
    docker:
      - image: circleci/python:3.6
    environment:
      JENKINS_URL: https://ci.sandbox.datagov.us
    steps:
      - checkout
      - deploy:
          name: Trigger Jenkins deploy
          command: bin/jenkins_build deploy-ci-app-catalog-next
  
  test_importer: 
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: tests
          command: make test-import-tool

  # Test the shared CI setup script completes successfully
  test_legacy_ci_script:
    machine:
      image: circleci/classic:201708-01
    steps:
      - checkout
      - run:
          name: Setup CI with legacy script
          command: |
            cp ckan/test-catalog-next.ini tools/ci-scripts/
            cd tools/ci-scripts
            ./circleci-build-catalog-next.bash

  docker_publish_catalog:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image-catalog.tar
      - run:
          name: Tag and publish catalog image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push datagov/catalog.data.gov:latest

  docker_publish_solr:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load archived Docker SOLR image
          command: docker load -i /tmp/workspace/image-solr.tar
      - run:
          name: Tag and publish SOLR image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push datagov/catalog.data.gov.solr:latest
            

  docker_publish_db:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load archived Docker DB image
          command: docker load -i /tmp/workspace/image-db.tar
      - run:
          name: Tag and publish DB image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push datagov/catalog.data.gov.db:latest

workflows:
  version: 2
  commit:
    jobs:
      - test_legacy_ci_script
      - deploy-sandbox:
          requires:
            - test
          filters:
            branches:
              only: fcs
      - test_importer
      - test
      - docker_publish_catalog:
          requires:
            - test
          filters:
            branches:
              only: fcs
      - docker_publish_solr:
          requires:
            - test
          filters:
            branches:
              only: fcs
      - docker_publish_db:
          requires:
            - test
          filters:
            branches:
              only: fcs
