version: 2.1

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: build
          command: make build
      - run:
          name: Archive Catalog Docker image
          command: docker save -o image-catalog.tar datagov/catalog.data.gov:latest
      - run:
          name: Archive Solr Docker image
          command: docker save -o image-solr.tar datagov/catalog.data.gov.solr:latest
      - run:
          name: Archive DB Docker image
          command: docker save -o image-db.tar datagov/catalog.data.gov.db:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./image-catalog.tar
            - ./image-solr.tar
            - ./image-db.tar
      - run: 
          name: lint and test
          command: |
            docker-compose up -d
            make lint-all
            make quick-bat-test
  
  test_importer: 
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: tests 
          command: make test-import-tool
  
  start_ckan_28:
    machine:
      image: circleci/classic:201708-01
    steps:
      - checkout
      - run:
          name: Start CKAN 2.8
          command: |
            cp ckan/test-catalog-next.ini tools/ci-scripts/
            cd tools/ci-scripts
            ./circleci-build-catalog-next.bash

workflows:
  version: 2
  commit:
    jobs:
      - start_ckan_28
      - test_importer
      - test
