version: 2.1
jobs:
  bat_test:
    machine: true
    steps:
      - checkout
      - run: make test
      
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make build ci
      - run: make lint-all
      - run: make test-extensions

  deploy-sandbox:
    docker:
      - image: circleci/python:3.6
    environment:
      JENKINS_URL: https://ci.sandbox.datagov.us
    steps:
      - checkout
      - deploy:
          name: Trigger Jenkins deploy
          command: bin/jenkins_build deploy-ci-app-catalog-next
  
  test_importer: 
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: tests 
          command: make test-import-tool

workflows:
  version: 2
  commit:
    jobs:
      - build
      - deploy-sandbox:
          requires:
            - build
          filters:
            branches:
              only: master
      - test_importer
      - bat_test
