---
name: Check Stuck Harvest Jobs

on:   # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      environ:
      description: 'Environment:'
      required: true
      type: choice
      options:
        - development
        - staging
        - prod

jobs:
  db-solr-sync:
    name: Check Stuck Harvest Jobs
    runs-on: ubuntu-latest
    environment: ${{inputs.environ}}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run task
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            cf run-task catalog-admin
            --command "ckan geodatagov check-stuck-jobs"
            --name 'check-stuck-jobs'
            -m 2G -k 1500M
          cf_org: gsa-datagov
          cf_space: ${{ inputs.environ }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: monitor task output
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            tools/monitor_cf_logs.sh catalog-admin 'check-stuck-jobs'
          cf_org: gsa-datagov
          cf_space: ${{ inputs.environ }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: Create Issue if it fails 😢
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
          GITHUB_JOB: ${{ toJson(github)['job'] }}
          GITHUB_ATTEMPTS: ${{ github.run_attempt }}
          LAST_COMMIT: ${{ github.sha }}
          LAST_RUN_BY: ${{ github.actor }}
          RUN_ID: ${{ github.run_id }}
        with:
          filename: .github/stuck_jobs.md
          assignees: ${{ github.actor }}
          update_existing: true
