---
name: 4 - Automated CKAN Jobs

on:   # yamllint disable-line rule:truthy
  schedule:
    - cron: '30 7 * * *'       # Tracking Update -- every day at 7:30am UTC
    - cron: '0 3 * * *'        # S3 Sitemap Update -- every day at 3am UTC
    - cron: '11/15 * * * *'    # Harvester Check -- every 15 mins
    - cron: '0 4 * * *'        # DB-Solr-Sync -- every day at 4am UTC
    - cron: '0 5 * * *'        # Check Stuck Jobs -- every day at 5am UTC

jobs:
  ckan-auto-command:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        schedule: ['30 7 * * *', '0 3 * * *', '11/15 * * * *', '0 4 * * *', '0 5 * * *']   # yamllint disable-line rule:line-length
        environ: [development, staging, prod]
        include:
          - app: catalog-admin
          - monitor: true
          - schedule: '30 7 * * *'
            command: "ckan geodatagov tracking-update"
          - schedule: '11/15 * * * *'
            command: "ckan harvester run"
          - schedule: '0 4 * * *'
            command: "ckan geodatagov db-solr-sync"
          - schedule: '0 5 * * *'
            command: "ckan geodatagov check-stuck-jobs"
          - schedule: '0 3 * * *'
            command: "ckan geodatagov sitemap-to-s3"
          - schedule: '0 3 * * *'
            app: catalog-gather
          - schedule: '11/15 * * * *'
            monitor: false
          - schedule: '0 3 * * *'
            monitor: false
          - environ: development
            ram: 1G
          - environ: staging
            ram: 3G
          - environ: prod
            ram: 3G
        exclude:
          - schedule: '0 3 * * *'
            environ: development
          - schedule: '0 3 * * *'
            environ: staging
          - schedule: '0 5 * * *'
            environ: development
    name: ${{ matrix.command }} - ${{matrix.environ}}
    runs-on: ubuntu-latest
    environment: ${{matrix.environ}}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set Unique Command Name
        # yamllint disable rule:line-length
        run: |
          INSTANCE_NAME="$(echo ${{ matrix.command }}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT})"
          echo "INSTANCE_NAME=${INSTANCE_NAME}" | tee -a $GITHUB_ENV
          # yamllint enable rule:line-length
      - name: ${{ matrix.command }}
        if: ${{ github.event.schedule == matrix.schedule }}
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            cf run-task ${{ matrix.app }}
            --command "${{ matrix.command }}"
            --name "$INSTANCE_NAME"
            -m ${{ matrix.ram }} -k 2G
          cf_org: gsa-datagov
          cf_space: ${{ matrix.environ }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: monitor task output
        if: ${{ matrix.monitor && github.event.schedule == matrix.schedule }}
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            tools/monitor_cf_logs.sh ${{ matrix.app }} $INSTANCE_NAME
          cf_org: gsa-datagov
          cf_space: ${{ matrix.environ }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: Create Issue if it fails 😢
        if: ${{ failure() && github.event.schedule == '0 5 * * *' }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
          GITHUB_JOB: ${{ toJson(github)['job'] }}
          GITHUB_ATTEMPTS: ${{ github.run_attempt }}
          LAST_COMMIT: ${{ github.sha }}
          LAST_RUN_BY: ${{ github.actor }}
          RUN_ID: ${{ github.run_id }}
          JOB_ID: ${{ github.job_id }}
        with:
          filename: .github/stuck_jobs.md
          assignees: ${{ github.actor }}
          update_existing: true
