---
name: 4 - Automated CKAN Jobs

on:   # yamllint disable-line rule:truthy
  schedule:
    - cron: '30 7 * * *'       # Tracking Update -- every day at 2:30am EST
    - cron: '0 2 * * *'        # S3 Sitemap Update -- every day at 7pm EST
    - cron: '4/15 5-23 * * *'  # Harvester Check -- every 15 mins between 12am and 6pm EST
    - cron: '0 3 * * *'        # DB-Solr-Sync -- every day at 10pm EST
    - cron: '0 4 * * *'        # Check Stuck Jobs -- every day at 11pm EST

env:
  ERROR: false
  # Make sure 'schedule-cron' matches these varaibles.
  SCHEDULE_TRACKING: '30 7 * * *'
  SCHEDULE_SITEMAP: '0 2 * * *'
  SCHEDULE_HARVESTING: '4/15 5-23 * * *'
  SCHEDULE_STUCK_JOBS: '0 3 * * *'
  SCHEDULE_DBSOLR_SYNC: '0 4 * * *'

jobs:
  ckan-auto-command:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        schedule: [
          $SCHEDULE_TRACKING, $SCHEDULE_SITEMAP, $SCHEDULE_HARVESTING,
          $SCHEDULE_STUCK_JOBS, $SCHEDULE_DBSOLR_SYNC
        ]
        environ: [development, staging, prod]
        include:
          # Default app to run tasks on
          - app: catalog-admin
          # Default timeout for task to raise issue
          - error_seconds: 22000
          # Default monitor everything
          - monitor: true
          # Attach commands to schedule
          - schedule: $SCHEDULE_TRACKING
            command: "ckan geodatagov tracking-update"
          - schedule: $SCHEDULE_HARVESTING
            command: "ckan harvester run"
          - schedule: $SCHEDULE_DBSOLR_SYNC
            command: "ckan geodatagov db-solr-sync"
          - schedule: $SCHEDULE_STUCK_JOBS
            command: "ckan geodatagov check-stuck-jobs"
          - schedule: $SCHEDULE_SITEMAP
            command: "ckan geodatagov sitemap-to-s3"
          # Run sitemap-to-s3 on catalog-gather
          - schedule: $SCHEDULE_SITEMAP
            app: catalog-gather
          # Don't monitor 'harvester run'
          - schedule: $SCHEDULE_HARVESTING
            monitor: false
          # Don't monitor 'sitemap-to-s3'
          - schedule: $SCHEDULE_SITEMAP
            monitor: false
          # If tracking update takes longer than 210 mins, make an issue
          - schedule: $SCHEDULE_TRACKING
            error_seconds: 12600
          # If db solr sync takes longer than 30 mins, make an issue
          - schedule: $SCHEDULE_DBSOLR_SYNC
            error_seconds: 1800
          # Adjust RAM per space
          - environ: development
            ram: 1G
          - environ: staging
            ram: 3G
          - environ: prod
            ram: 3G
        exclude:
          # Don't run 'sitemap-to-s3' on development/staging
          - schedule: $SCHEDULE_SITEMAP
            environ: development
          - schedule: $SCHEDULE_SITEMAP
            environ: staging
          # Don't run 'db-solr-sync' + 'check-stuck-jobs' on development
          - schedule: $SCHEDULE_DBSOLR_SYNC
            environ: development
          - schedule: $SCHEDULE_STUCK_JOBS
            environ: development
    name: ${{ matrix.command }} - ${{matrix.environ}}
    runs-on: ubuntu-latest
    environment: ${{matrix.environ}}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set Unique Command Name
        # yamllint disable rule:line-length
        run: |
          INSTANCE_NAME="$(echo ${{ matrix.command }}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT} | tr -d ' ')"
          echo "INSTANCE_NAME=${INSTANCE_NAME}" | tee -a $GITHUB_ENV
          START=$SECONDS | tee -a $GITHUB_ENV
          # yamllint enable rule:line-length
      - name: ${{ matrix.command }}
        if: ${{ github.event.schedule == matrix.schedule }}
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            cf run-task ${{ matrix.app }}
            --command "${{ matrix.command }}"
            --name "$INSTANCE_NAME"
            -m ${{ matrix.ram }} -k 2G
          cf_org: gsa-datagov
          cf_space: ${{ matrix.environ }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: monitor task output
        if: ${{ matrix.monitor && github.event.schedule == matrix.schedule }}
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            tools/monitor_cf_logs.sh ${{ matrix.app }} $INSTANCE_NAME
          cf_org: gsa-datagov
          cf_space: ${{ matrix.environ }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: check runtime
        run: |
          ELAPSED=$(( SECONDS - START))
          echo "$START, $SECONDS, $ELAPSED"
          if [[ $ELAPSED > ${{ matrix.error_seconds }} ]]; then ERROR=true | tee -a $GITHUB_ENV; fi;
      - name: Create Issue if it fails 😢
        if: ${{ failure() || (env.ERROR == true) }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
          GITHUB_JOB: ${{ toJson(github)['job'] }}
          GITHUB_ATTEMPTS: ${{ github.run_attempt }}
          LAST_COMMIT: ${{ github.sha }}
          LAST_RUN_BY: ${{ github.actor }}
          RUN_ID: ${{ github.run_id }}
          COMMAND: ${{ matrix.command }}
          SCHEDULE: ${{ matrix.schedule }}
          ENVIRONMENT: ${{ matrix.environ }}
        with:
          filename: .github/automated_ckan_error.md
          assignees: ${{ github.actor }}
          update_existing: true
