---
name: commit

on:
  push:

jobs:
  lint-actions:
    name: Lint Yaml
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Lint GitHub Actions
        run: yamllint .github/workflows/
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make build
      - name: test
        run: make test
      - name: cypress-artifacs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            ./e2e/cypress/screenshots/
            ./e2e/cypress/videos/

  test_importer:
    name: test importer
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: x64
      - name: test_importer
        run: make test-import-tool

  vendor:
    name: vendor dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: vendor dependencies
        run: ./vendor-requirements.sh build
      - uses: actions/upload-artifact@v2
        with:
          name: python-vendored
          path: vendor/
          if-no-files-found: error

  create-cloudgov-services-development:
    if: github.ref == 'refs/heads/develop'
    name: create services (development)
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create services
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: ./create-cloudgov-services.sh
          cf_org: gsa-datagov
          cf_space: development
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}

  deploy-development:
    if: github.ref == 'refs/heads/develop'
    name: deploy (development)
    environment: development
    strategy:
      matrix:
        app: [
          catalog-web,
          catalog-admin,
          catalog-gather,
          catalog-fetch,
          catalog-proxy
        ]
        include:
          - app: catalog-web
            smoketest: true
    runs-on: ubuntu-latest
    needs:
      - vendor
      - create-cloudgov-services-development
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: python-vendored
          path: vendor
      - name: deploy ${{ matrix.app }}
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            cf push ${{ matrix.app }}
            --vars-file vars.development.yml
            --strategy rolling
          cf_org: gsa-datagov
          cf_space: development
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: smoke test
        if: ${{ matrix.smoketest }}
        run: |
          sleep 10
          curl --fail --silent https://catalog-dev-datagov.app.cloud.gov\
          /api/action/status_show?$(date +%s)
