---
name: commit

on:
  push:


jobs:
  test:
    name: lint and test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make build
      - name: Archive Catalog Docker image
        run: docker save -o ckan/image-catalog.tar datagov/catalog.data.gov:latest
      - name: Archive Solr Docker image
        run: docker save -o ckan/image-solr.tar datagov/catalog.data.gov.solr:latest
      - name: Archive DB Docker image
        run: docker save -o ckan/image-db.tar datagov/catalog.data.gov.db:latest
      - uses: actions/upload-artifact@v2
        with:
          name: docker-images
          path: |
            ckan/image-catalog.tar
            ckan/image-solr.tar
            ckan/image-solr.tar
          if-no-files-found: error
      - name: lint and test
        run: |
          docker-compose up -d
          make lint-all
          make quick-bat-test

  test_importer:
    name: test importer
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: x64
      - name: test_importer
        run: make test-import-tool

  vendor:
    name: vendor dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: vendor dependencies
        run: ./vendor-requirements.sh
      - uses: actions/upload-artifact@v2
        with:
          name: python-vendored
          path: vendor/
          if-no-files-found: error

  deploy-development:
    if: github.ref == 'refs/heads/develop'
    name: deploy (development)
    environment: development
    runs-on: ubuntu-latest
    needs:
      - test
      - vendor
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: python-vendored
          path: vendor
      - name: deploy
        uses: usds/cloud-gov-cli@master
        with:
          command: push catalog --vars-file vars.development.yml --strategy rolling
          org: gsa-datagov
          space: development
          user: ${{secrets.CF_SERVICE_USER}}
          password: ${{secrets.CF_SERVICE_AUTH}}
      - name: smoke test
        run: |
          sleep 10
          curl --fail --silent https://catalog-dev-datagov.app.cloud.gov/api/action/status_show?$(date +%s)

  ghcr_publish_catalog:
    # TODO: move to publish.yml
    name: publish catalog on DockerHub
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: publish catalog.data.gov
        uses: docker/build-push-action@v2
        with:
          context: ckan
          push: true
          tags: ghcr.io/gsa/catalog.data.gov:latest
  
  ghcr_publish_solr:
    # TODO: move to publish.yml
    name: publish catalog on DockerHub
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: publish catalog.data.gov.solr
        uses: docker/build-push-action@v2
        with:
          context: solr
          push: true
          tags: ghcr.io/gsa/catalog.data.gov.solr:latest