name: DB Solr Sync

on:
  workflow_dispatch:
    inputs:
      options:
        description: 'Command options:'
        required: false
        type: choice
        options:
          - 'Dryrun'
          - 'Only cleanup solr'
          - 'Only update solr'
          - 'Both'
      environ:
        description: 'Environment:'
        required: true
        type: choice
        options:
          - development
          - staging
          - prod

jobs:
  db-solr-sync:
    name: DB Solr Sync (${{github.event.inputs.environ}})
    environment: ${{github.event.inputs.environ}}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Dry Run
        if: ${{ github.event.inputs.options == 'Dryrun' }}
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            cf run-task catalog-admin
              --command "ckan geodatagov db-solr-sync --dryrun"
              --name 'db-solr-sync (CI)' -m 3G
          cf_org: gsa-datagov
          cf_space: ${{github.event.inputs.environ}}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: Only Cleanup Solr
        if: ${{ github.event.inputs.options == 'Only cleanup solr' }}
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            cf run-task catalog-admin
              --command "ckan geodatagov db-solr-sync --cleanup_solr"
              --name 'db-solr-sync (CI)' -m 3G
          cf_org: gsa-datagov
          cf_space: ${{github.event.inputs.environ}}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: Only Update Solr
        if: ${{ github.event.inputs.options == 'Only update solr' }}
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            cf run-task catalog-admin
              --command "ckan geodatagov db-solr-sync --update_solr"
              --name 'db-solr-sync (CI)' -m 3G
          cf_org: gsa-datagov
          cf_space: ${{github.event.inputs.environ}}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: Do Both
        if: ${{ github.event.inputs.options == 'Both' }}
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            cf run-task catalog-admin
              --command "ckan geodatagov db-solr-sync --cleanup_solr --update_solr"
              --name 'db-solr-sync (CI)' -m 3G
          cf_org: gsa-datagov
          cf_space: ${{github.event.inputs.environ}}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: monitor task output
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: tools/monitor_cf_logs.sh catalog-admin 'db-solr-sync (CI)' 'geodatagov'
          cf_org: gsa-datagov
          cf_space: ${{github.event.inputs.environ_cf}}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
