---
name: publish & deploy

on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  ghcr_publish:
    name: Publish Images on GHCR
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [ckan, solr, postgresql]
        include:
          - image: ckan
            name: catalog.data.gov
            tag: ghcr.io/gsa/catalog.data.gov:latest
          - image: solr
            name: catalog.data.gov.solr
            tag: ghcr.io/gsa/catalog.data.gov.solr:latest
          - image: postgresql
            name: catalog.data.gov.db
            tag: ghcr.io/gsa/catalog.data.gov.db:latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: publish ${{ matrix.name }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.image }}
          push: true
          tags: ${{ matrix.tag }}

  vendor:
    name: vendor dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: vendor dependencies
        run: ./vendor-requirements.sh build
      - uses: actions/upload-artifact@v3
        with:
          name: python-vendored
          path: vendor/
          if-no-files-found: error

  create-cloudgov-services-staging:
    name: create services (staging)
    uses: ./.github/workflows/create-services-template.yml
    with:
      environ: staging
    secrets: inherit

  create-cloudgov-services-prod:
    name: create services (prod)
    uses: ./.github/workflows/create-services-template.yml
    with:
      environ: prod
    secrets: inherit

  deploy-staging:
    name: deploy (staging)
    needs:
      - create-cloudgov-services-staging
      - vendor
    uses: ./.github/workflows/deploy-template.yml
    with:
      environ: staging
      app_url: https://catalog-stage-datagov.app.cloud.gov
    secrets: inherit

  deploy-prod:
    name: deploy (prod)
    needs:
      - vendor
      - create-cloudgov-services-prod
      - deploy-staging
    uses: ./.github/workflows/deploy-template.yml
    with:
      environ: prod
      app_url: https://catalog.data.gov
    secrets: inherit
