---
name: restart application

on:
  schedule:
    - cron: '11/30 * * * *'

jobs:
   # restart-staging:
   #   name: restart (staging)
   #   environment: staging
   #   runs-on: ubuntu-latest
   #   steps:
   #     - name: checkout
   #       uses: actions/checkout@v2
   #     - name: restart catalog-web
   #       uses: cloud-gov/cg-cli-tools@main
   #       with:
   #         command: cf restart catalog-web --strategy rolling
   #         cf_org: gsa-datagov
   #         cf_space: staging
   #         cf_username: ${{secrets.CF_SERVICE_USER}}
   #         cf_password: ${{secrets.CF_SERVICE_AUTH}}
   #     - name: restart catalog-admin
   #       uses: cloud-gov/cg-cli-tools@main
   #       with:
   #         command: cf restart catalog-admin --strategy rolling
   #         cf_org: gsa-datagov
   #         cf_space: staging
   #         cf_username: ${{secrets.CF_SERVICE_USER}}
   #         cf_password: ${{secrets.CF_SERVICE_AUTH}}
   #     # - name: restart gather
   #     #   uses: cloud-gov/cg-cli-tools@main
   #     #   with:
   #     #     command: cf restart catalog-gather
   #     #     cf_org: gsa-datagov
   #     #     cf_space: staging
   #     #     cf_username: ${{secrets.CF_SERVICE_USER}}
   #     #     cf_password: ${{secrets.CF_SERVICE_AUTH}}
   #     - name: restart fetch
   #       uses: cloud-gov/cg-cli-tools@main
   #       with:
   #         command: cf restart catalog-fetch
   #         cf_org: gsa-datagov
   #         cf_space: staging
   #         cf_username: ${{secrets.CF_SERVICE_USER}}
   #         cf_password: ${{secrets.CF_SERVICE_AUTH}}
   #     - name: smoke test
   #       run: |
   #         sleep 10
   #         curl --fail --silent https://catalog-stage-datagov.app.cloud.gov/api/action/status_show?$(date +%s)

  restart-prod:
    name: restart (prod)
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: restart catalog-web
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: cf restart catalog-web --strategy rolling
          cf_org: gsa-datagov
          cf_space: prod
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: restart catalog-admin
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: cf restart catalog-admin --strategy rolling
          cf_org: gsa-datagov
          cf_space: prod
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: restart gather
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: |
            # Utility Functions
            # Get the number of lines in the log (int)
            log_count () { cf logs --recent catalog-gather | wc -l; }
            # Get the time of the last line in the log (int)
            log_last_time () { cf logs --recent catalog-gather | tail -n 1 | awk '{split($0,time,":"); print time[2]}'; }
            # Get CPU reading
            cpu_integer () { cf app catalog-gather | tail -n 1 | awk '{ split($4,cpu,"."); print cpu[1]}'; }
            cpu_decimal () { cf app catalog-gather | tail -n 1 | awk '{ split($4,cpu,"."); split(cpu[2],dec,"%"); print dec[1]}'; }

            # Check last log
            # If there are only two lines, there are no logs
            if [[ $((`log_count` > 2)) == '1' ]]; then
              # if the timestamp is younger than half of the restart interval
              if [[ $((`log_last_time` % 30 < 15)) == '1' ]]; then
                echo "Logs are too new!  Not going to restart"
                exit 1
              fi
            fi
            # if CPU usage is less then 1%, it's okay to restart
            if [[ $((`cpu_integer` < 1)) ]]; then
              cf restart catalog-gather
            fi
          cf_org: gsa-datagov
          cf_space: prod
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: restart fetch
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: cf restart catalog-fetch
          cf_org: gsa-datagov
          cf_space: prod
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: smoke test
        run: |
          sleep 10
          curl --fail --silent https://catalog-prod-datagov.app.cloud.gov/api/action/status_show?$(date +%s)
