---
name: restart application

on:   # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: '11/30 * * * *'

jobs:
  restart-staging:
    name: restart (staging)
    uses: gsa/data.gov/.github/workflows/app-restart-template.yml@main
    with:
      environ: staging
      app_names: "{\"include\":[{\"app\":\"catalog-proxy\"},{\"app\":\"catalog-web\"},{\"app\":\"catalog-admin\"},]}"   # yamllint disable-line rule:line-length
      # TODO what to do about gather & fetch
    secrets: inherit

  restart-production:
    name: restart (production)
    uses: gsa/data.gov/.github/workflows/app-restart-template.yml@main
    with:
      environ: production
      app_names: "{\"include\":[{\"app\":\"catalog-proxy\"},{\"app\":\"catalog-web\"},{\"app\":\"catalog-admin\"},]}"   # yamllint disable-line rule:line-length
      # TODO what to do about gather & fetch
    secrets: inherit
