---
name: 3 - Restart Apps

on:
  workflow_dispatch:
  schedule:
    - cron: '11/30 * * * *'

jobs:
  restart-staging:
    name: restart (staging)
    uses: gsa/data.gov/.github/workflows/app-restart-template.yml@delete1
    with:
      environ: staging
      app_names: "{\"include\":[{\"app\":\"catalog-proxy\"},{\"app\":\"catalog-gather\"},{\"app\":\"catalog-fetch\"},{\"app\":\"catalog-web\"},{\"app\":\"catalog-admin\"},]}"
    secrets: inherit
