---
name: restart application

on:   # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: '11/30 * * * *'

jobs:
  restart-dev-for-testing:
    name: restart (dev)
    uses: gsa/data.gov/.github/workflows/app-restart-template.yml@main
    with:
      environ: development
      app_names: "{\"include\":[{\"app\":\"catalog-proxy\"},{\"app\":\"catalog-web\"},{\"app\":\"catalog-admin\"},]}"   # yamllint disable-line rule:line-length
      # TODO what to do about gather & fetch
    secrets: inherit
