---
name: s3 to sitemap

on:   # yamllint disable-line rule:truthy
  workflow_dispatch:
  # TODO: enable schedule below
  # schedule:
  # - cron: '0 4 * * *' # every day at 4am UTC

jobs:
  s3-to-sitemap:
    name: s3-to-sitemap
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run ckan-sitemap
        with:
          command: >
            cf run-task catalog-admin
            --command "ckan geodatagov sitemap-to-s3"
            --name sitemap
            -m 3G -k 3G
      # TODO remove tmate option
      - name: Setup tmate session on fail
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
