---
name: Check for Snyk Vulnerabilities

on:   # yamllint disable-line rule:truthy
  workflow_dispatch:
  # schedule:
  #   - cron: '0 12 * * *'  # every day at 12pm UTC

jobs:
  snyk:
    name: snyk test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          npm install snyk -g;
          sudo apt-get update -y;
          sudo apt-get install -y \
            openssl libssl-dev libffi-dev pkg-config libxml2-dev \
            libxmlsec1-dev libxmlsec1-openssl swig build-essential \
            libgeos-dev proj-bin;
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
          PY_VERSION=python3.8
          sudo apt-get -y install python-dev ${PY_VERSION}-distutils;
          sudo apt-get -y install ${PY_VERSION}
          curl -sSL https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
          ${PY_VERSION} /tmp/get-pip.py
          pip3.8 install -r requirements.txt;
      - name: Run Snyk Scan
        run: >
          # Run scan
          snyk test --file=requirements.txt --json-file-output=scan.json;

          # Exit if no vulnerabilities
          [[ "$(jq '.ok' scan.json)" == "true" ]] && exit 0;
          while read -r fix
          do
            package=$(echo $fix | cut -d "=" -f 1)
            sed -i "/${package}.*/d" ckan/requirements.in
            sed -i "/${package}.*/d" ckan/requirements.txt
            echo $fix >> ckan/requirements.in
          done <<< $(jq -r '.vulnerabilities[] | .moduleName,.fixedIn[]'
            scan.json | sed 'N;s/\n/>=/');

          make update-dependencies;
          exit 1
      - name: Create Pull Request
        if: ${{ failure() }}
        id: scpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          commit-message: Update Pip Requirements
          committer: Data.gov Github <datagovhelp@gsa.gov>
          author: ${{ github.actor }} <datagovhelp@gsa.gov>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: '[Snyk + GH Actions] Update requirements'
          body: |
            Update requirements
            - Updated `requirements.in` + `requirements.txt`
            - Auto-generated by [snyk.yml][1]

            [1]: https://github.com/gsa/catalog.data.gov/\
            .github/workflows/snyk.yml
          labels: |
            requirements
            automated pr
            snyk
          reviewers: GSA/data-gov-team
          team-reviewers: |
            owners
            maintainers
          draft: false
